### ISSUE TITLE
Prefill "add torrent link" dialogue with clipboard contents

### ISSUE THREAD

**Issue by 9ary** [equeim/tremotesf-android#135]
Very nice app, thank you for working on it. :)

I have a small feature request: when I want to add a torrent by link, I pretty much always paste a link from my clipboard (I'm not sure anyone types links in manually, do they? :P). It would be a nice QoL improvement if the link could be filled in from the clipboard automatically instead of having to paste manually.
An acceptable middle-ground would be to show a paste button next to the input field.

**Comment by simba83** [comment]
I always download the .torrents on the phone and open them using the app. Works perfectly every time.

**Comment by 9ary** [comment]
Yes, that works fine, but adding a torrent by URI is still a feature that exists and could use improvement. It'd also be helpful for magnet links.

**Comment by simba83** [comment]
It works here as far as I could seen android 13  and latest app build (4days old).

**Comment by 9ary** [comment]
I'm not sure you understood the feature request here. When I click "add torrent link", I want the clipboard contents to be inserted into the dialogue. I see no indication that this has been implemented since this issue was opened.

This isn't specifically about magnet links, which, as I noted, the app is already a URL handler for. Magnet links *work*.

**Comment by simba83** [comment]
It's fully possible I understand you wrong.
This is how it looks for me.

![Screenshot_20221105-215351.png](https://user-images.githubusercontent.com/1194513/200141005-7b7de5b0-2438-464a-90fb-aadd89d664c0.png)

**Comment by 9ary** [comment]
Yes, I'm asking for the clipboard contents to be pre-filled into the input, instead of having to paste manually like you're showing. This is fairly common in other torrent clients (even the official Transmission GUI on desktop platforms does it).

I believe the changes required are fairly simple, I might actually try to make a pull request for it once my computer is fixed.

**Comment by equeim** [comment]
> Yes, I'm asking for the clipboard contents to be pre-filled into the input, instead of having to paste manually like you're showing. This is fairly common in other torrent clients (even the official Transmission GUI on desktop platforms does it).
> 
> I believe the changes required are fairly simple, I might actually try to make a pull request for it once my computer is fixed.

FYI I'm working on it right now. I'm also going to implement drag&drop (adding torrents via drop gestures from other apps, e.g. Android's built-in file manager) since it shares the same code as clipboard.
