### ISSUE TITLE
New release won't install

### ISSUE THREAD

**Issue by peaveyman** [equeim/tremotesf-android#14]
I downloaded both the fdroid and google release and added them to my phone. Trying to install either of them tells me the app isn't compatible with my phone. I have an LG V6.

**Comment by equeim** [comment]
You mean LG G6? That's strange, it should be supported. Could you cpature system log and send it to me (i.e. using MatLog app. Unfortunately, due to Android restrictions your device should be rooted or you will need to use ADB)?

**Comment by peaveyman** [comment]
I will try when I back to my computer.

**Comment by peaveyman** [comment]
I have it working. The problem was the version I had wasn't installed thru the play store. I removed it and installed from the play store and it gave me the new version.
