### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Sak94664** [equeim/tremotesf-android#15]
![screenshot_20180619-091110](https://user-images.githubusercontent.com/10434184/41570341-f42c19b8-73a0-11e8-9453-4a2db91bef25.png)
Fdroid version 1.7.0 came up recently,but when I finished downloading it and trying to install it,it says "Failed to install due to unknown error."And I tried to uninstall previous version and install the latest version,the problem persists.

OS:LineageOS 14.1 
Model:Redmi Note 3

**Comment by Nautigsam** [comment]
Same here, tremotesf 1.7.0 and fdroid 1.2.2 on Android 7.0.

**Comment by equeim** [comment]
That's F-Droid bug, it incorrectly calls zipalign when building APK. It can take some time to get fixed, so you can download new version from [releases](https://github.com/equeim/tremotesf-android/releases/tag/1.7.0) page, but keep in mind that it uses different signature that F-Droid build, so you will need to remove previous version first (and also remove my build before reinstalling from F-Droid in future).

**Comment by Sak94664** [comment]
Thanks :)
