### ISSUE TITLE
1.7.0 install fails

### ISSUE THREAD

**Issue by wilyarti** [equeim/tremotesf-android#16]
Install fails on fdroid and with a downloaded APK from the fdroid website. APK is 16mb compared to 2mb for the 1.6 version.

**Comment by equeim** [comment]
It's a bug in F-Droid. It has been fixed, but it will take several days for F-Droid to rebuild package automatically on schedule. You can install new version from [Releases](https://github.com/equeim/tremotesf-android/releases) page, but you will need to remove previous installed version from F-Droid first (and you will need to remove my APK before you update from F-Droid).
