### ISSUE TITLE
own-CA-signed certificate cannot be used

### ISSUE THREAD

**Issue by otommod** [equeim/tremotesf-android#165]
In my transmission server, I use a certificate generated by [mkcert](https://mkcert.org/), in other words, it's signed by my own CA (which is obviously in none of the trusted CAs lists).

Tremotesf fails with `The issuer certificate of a locally looked up certificate could not be found`

I've tried both giving the certificate to the app as a self-signed certificate as well as setting my CA in Android as a whole and neither works.

**Comment by equeim** [comment]
Try to add your whole certificate chain in self-signed certificate field in connection settings. Tremotesf would parse them all and ignore self-signed and hostname mismatch errors for all of them.

**Comment by otommod** [comment]
I was not sending the full chain certificate from my reverse proxy (and I was getting the error `QSslError::UnableToGetLocalIssuerCertificate`.)

Fixing this (sending the full chain) fixed my issue!
