### ISSUE TITLE
Connection error after app hide

### ISSUE THREAD

**Issue by abubaca4** [equeim/tremotesf-android#194]
![Screenshot_20230212_210516_org equeim tremotesf](https://user-images.githubusercontent.com/55701175/218573746-a21e95dd-650e-455a-affa-4ed5183f55dc.jpg)
After tap button work good
Https conection with nginx, auth enabled

Step to reproduce: open app, wait untill connect, hide app, open it again(maby need wait 10s)
I think app have to reconnect without button press

**Comment by otaconix** [comment]
@equeim: I've been running a custom build that includes the changes in https://github.com/equeim/libtremotesf/pull/172 for a while now, and I personally haven't seen this since.

**Comment by abubaca4** [comment]
Solved with last update
