### ISSUE TITLE
Selected files with same priority are reported as 'mixed'

### ISSUE THREAD

**Issue by Mrnofish** [equeim/tremotesf-android#231]
1. Add torrent with multiple files
2. Change priorities so that e.g. the first file is high priority, the second file is normal and the remainder is low
3. Now select manually all same priority (e.g. low) files
4. Tap on the priority button and see the files are reported as 'Mixed'
5. Deselect all files
6. Select each file individually and verify that now they are reported individually at the correct priority (e.g. low)
7. Alternatively, verify that the files are correctly prioritized using a different client

Environment:
- Tremotesf 2.9.1
- Transmission 3.00
- LOS 20 / Android 13

**Comment by mvastola** [comment]
I get this _whenever_ I select multiple files, even if none of them were ever changed from "normal"
