### ISSUE TITLE
Feature request:rename torrent

### ISSUE THREAD

**Issue by Sak94664** [equeim/tremotesf-android#24]
sometimes torrent name is too long (for Linux ext4 and NTFS the limit is 255,but I cannot find the solution on the Internet)
And then I want to rename it so that I can download from other peers.

It is available in transmission webui.But it might be easier if it is implemented in this app.
Thanks in advance :)

**Comment by equeim** [comment]
Technically you can rename torrents in Tremotesf. You just need to go to files tag in torrent's properties activity and rename root file/directory. I guess that it would be more convenient to add a shortcut for this in torrent's context menu on main screen if that's what you mean in this issue.

**Comment by Sak94664** [comment]
Oh,sorry,I found that this bug "filename too long" is a bug to be fixed in transmission 3.0 milestone.(according to https://github.com/transmission/transmission/issues/122)

Could you please add this function when in "add torrents" screen?

**Comment by Sak94664** [comment]
By the way,It seems that enabling alternative speed limits in the main screen doesn't work.(after tapping "Alternative speed limits,nothing showed up and nothing changed.)

Should I open another issue for it?

**Comment by equeim** [comment]
Nah, I already fixed it.

**Comment by equeim** [comment]
>Could you please add this function when in "add torrents" screen?

It is planned, but not for the next version.

**Comment by Sak94664** [comment]
Thanks so much. :)
Now closing this issue
