### ISSUE TITLE
Rename folder or file when adding a torrent

### ISSUE THREAD

**Issue by retro-78** [equeim/tremotesf-android#27]
Hi

Thanks for new features for adding a new torrent.

I have noticed that I m unable to rename torrent contents when there is a single file or a single folder inside the torrent. I can't access to the option rename when adding the torrent. It is just possible after adding it .

Did you notice this issue ?

Thanks

**Comment by equeim** [comment]
Yeah, this is due to how Transmission remote protocol works. It is possible to workaround this, but I currently can't say when this feature will be available.

**Comment by equeim** [comment]
Yeah, this is due to how Transmission remote protocol works. It is possible to workaround this, but currently I can't say when this feature will be available (but I plan to add it).
