### ISSUE TITLE
Feature request: display full date and time details

### ISSUE THREAD

**Issue by TheUglyOne** [equeim/tremotesf-android#28]
I'd like to request the option to display timestamps on the torrent details tab as full dates and times. For example, instead of "23 hours ago" or "Feb 22, 2019", I would like to always see something along the lines of "Feb 22, 2019 at 9:05 PM" or "2019-02-22 09:05 PM"

This feature request applies to the "Last activity", "Created on", and "Added date" fields, as well as any other timestamp fields that might be added in the future. For example, it would also be amazing to have a "Completed on" field. (See the fourth screenshot from the [Transmission Remote](https://play.google.com/store/apps/details?id=net.yupol.transmissionremote.app) page to get a sense of what I'm trying to describe.)

P.S. I just discovered this app today and I'm already in love with it! Thanks for making such a great, open-source app! :-)

**Comment by zayn666** [comment]
i second this, would like it to be able to change it
