### ISSUE TITLE
Feature request: add multiple trackers at a time

### ISSUE THREAD

**Issue by demolg** [equeim/tremotesf-android#30]
I'd like to add lots of trackers. Currently it can only add trackers one by one. Usually, I would copy [tracker list](https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best.txt) to the software.

**Comment by peerless2012** [comment]
I need this feature too,hpoe to that.

**Comment by peerless2012** [comment]
@equeim It will be great to add trackers from url or edit/add trackers at one time.
