### ISSUE TITLE
Merge Error

### ISSUE THREAD

**Issue by alabotski** [equeim/tremotesf-android#302]
An error occurs when adding an existing torrent file
https://drive.google.com/drive/folders/19erzaEmqmg7TKhVKqJd0vjx18QWUpYDN?usp=sharing

[Screenshot_20240528-080356](https://github.com/equeim/tremotesf-android/assets/439337/371b57a5-a640-4487-ac3a-98472192e6fb)
[ERROR.txt](https://github.com/equeim/tremotesf-android/files/15468749/ERROR.txt)

**Comment by equeim** [comment]
Do you use Transmission older than 4.0?

**Comment by alabotski** [comment]
@equeim 
Hi the problem still presents
[Error﹕_  org.equeim.tremotesf.rpc.RpcRequestError$.txt](https://github.com/user-attachments/files/15943941/Error._.org.equeim.tremotesf.rpc.RpcRequestError.txt)
[Screenshot_20240623-104142](https://github.com/equeim/tremotesf-android/assets/439337/b7b31e51-c9a9-42ed-a47f-0e4894eee2ea)
[Screenshot_20240623-104227](https://github.com/equeim/tremotesf-android/assets/439337/d1b8bc36-1bf8-4409-90cc-ec0924bd41ef)

**Comment by alabotski** [comment]
Hi @equeim 

The problem still present 


![Screenshot_20241016-122247](https://github.com/user-attachments/assets/655a102c-1f6c-4251-955c-a020af1e2aa2)
![Screenshot_20241016-122237](https://github.com/user-attachments/assets/da5a39bb-81c8-4663-97a9-377012fb2ff5)
![Screenshot_20241016-122232](https://github.com/user-attachments/assets/8f8748b3-c052-4c04-8a93-152e4e51d278)
![Screenshot_20241016-122223](https://github.com/user-attachments/assets/4789415c-2278-42ac-bbb6-9a7aeae266db)

**Comment by alabotski** [comment]
Hi @equeim 
The problem still present

[Image](https://github.com/user-attachments/assets/6fb88e45-d8cb-4fc1-8da5-ae68394d3c74)
[Image](https://github.com/user-attachments/assets/55481f14-27f4-43b1-9bbd-dd441348c54d)

[Error.txt](https://github.com/user-attachments/files/19562445/Error.txt)
