### ISSUE TITLE
Bug Report: App crashed after viewing a specific torrent's peers&limits section

### ISSUE THREAD

**Issue by Sak94664** [equeim/tremotesf-android#33]
Hi,when I tried to view a specific torrent's peers&limits section in torrent details page,the app itself exited without any message.

But only one of my torrents has this problem,while others don't.

Here is the logcat taken from matlog app.

> 07-19 21:17:41.973 I/ActivityManager(839): START u0 {cmp=org.equeim.tremotesf/.torrentpropertiesactivity.TorrentPropertiesActivity (has extras)} from uid 10137
07-19 21:17:42.490 W/SurfaceFlinger(698): Attempting to set client state on removed layer: Surface(name=AppWindowToken{313ea9b token=Token{fb27eaa ActivityRecord{d03ad95 u0 org.equeim.tremotesf/.mainactivity.MainActivity t81}}})/@0x15abc6f - animation-leash#0
07-19 21:17:42.490 W/SurfaceFlinger(698): Attempting to set client state on removed layer: Surface(name=AppWindowToken{af51af7 token=Token{d6b06f6 ActivityRecord{2db3791 u0 org.equeim.tremotesf/.torrentpropertiesactivity.TorrentPropertiesActivity t81}}})/@0x9f09785 - animation-leash#0
07-19 21:17:42.490 W/SurfaceFlinger(698): Attempting to destroy on removed layer: Surface(name=AppWindowToken{313ea9b token=Token{fb27eaa ActivityRecord{d03ad95 u0 org.equeim.tremotesf/.mainactivity.MainActivity t81}}})/@0x15abc6f - animation-leash#0
07-19 21:17:42.490 W/SurfaceFlinger(698): Attempting to destroy on removed layer: Surface(name=AppWindowToken{af51af7 token=Token{d6b06f6 ActivityRecord{2db3791 u0 org.equeim.tremotesf/.torrentpropertiesactivity.TorrentPropertiesActivity t81}}})/@0x9f09785 - animation-leash#0
07-19 21:17:43.751 E/AndroidRuntime(21193): Process: org.equeim.tremotesf, PID: 21193
07-19 21:17:43.751 E/AndroidRuntime(21193): 	at org.equeim.tremotesf.utils.ArraySpinnerAdapterWithHeader.getItem(Adapters.kt:108)
07-19 21:17:43.751 E/AndroidRuntime(21193): 	at org.equeim.tremotesf.utils.ArraySpinnerAdapterWithHeader.getItem(Adapters.kt:105)
07-19 21:17:43.751 E/AndroidRuntime(21193): 	at org.equeim.tremotesf.utils.BaseSpinnerAdapter.getView(Adapters.kt:79)
07-19 21:17:43.754 W/ActivityManager(839):   Force finishing activity org.equeim.tremotesf/.torrentpropertiesactivity.TorrentPropertiesActivity
07-19 21:17:43.760 I/ActivityManager(839): Showing crash dialog for package org.equeim.tremotesf u0
07-19 21:17:44.263 W/ActivityManager(839): Activity pause timeout for ActivityRecord{2db3791 u0 org.equeim.tremotesf/.torrentpropertiesactivity.TorrentPropertiesActivity t81 f}
07-19 21:17:44.697 W/ActivityManager(839):   Force finishing activity org.equeim.tremotesf/.torrentpropertiesactivity.TorrentPropertiesActivity
07-19 21:17:44.709 W/ActivityManager(839):   Force finishing activity org.equeim.tremotesf/.mainactivity.MainActivity
07-19 21:17:44.717 E/ActivityManager(839): Found activity ActivityRecord{d03ad95 u0 org.equeim.tremotesf/.mainactivity.MainActivity t-1 f} in proc activity list using null instead of expected ProcessRecord{89b6589 21193:org.equeim.tremotesf/u0a137}
07-19 21:17:44.725 I/ActivityManager(839): Killing 21193:org.equeim.tremotesf/u0a137 (adj 199): crash
07-19 21:17:44.744 W/InputDispatcher(839): channel 'b89c82 org.equeim.tremotesf/org.equeim.tremotesf.torrentpropertiesactivity.TorrentPropertiesActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
07-19 21:17:44.744 E/InputDispatcher(839): channel 'b89c82 org.equeim.tremotesf/org.equeim.tremotesf.torrentpropertiesactivity.TorrentPropertiesActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
07-19 21:17:44.753 W/InputDispatcher(839): channel '2c3cb6a org.equeim.tremotesf/org.equeim.tremotesf.mainactivity.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
07-19 21:17:44.753 E/InputDispatcher(839): channel '2c3cb6a org.equeim.tremotesf/org.equeim.tremotesf.mainactivity.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
07-19 21:17:44.755 I/WindowManager(839): WIN DEATH: Window{b89c82 u0 org.equeim.tremotesf/org.equeim.tremotesf.torrentpropertiesactivity.TorrentPropertiesActivity}
07-19 21:17:44.755 W/InputDispatcher(839): Attempted to unregister already unregistered input channel 'b89c82 org.equeim.tremotesf/org.equeim.tremotesf.torrentpropertiesactivity.TorrentPropertiesActivity (server)'
07-19 21:17:44.757 I/WindowManager(839): WIN DEATH: Window{2c3cb6a u0 org.equeim.tremotesf/org.equeim.tremotesf.mainactivity.MainActivity}
07-19 21:17:44.757 W/InputDispatcher(839): Attempted to unregister already unregistered input channel '2c3cb6a org.equeim.tremotesf/org.equeim.tremotesf.mainactivity.MainActivity (server)'
07-19 21:17:44.885 W/SurfaceFlinger(698): Attempting to destroy on removed layer: 9ac7760 Application Error: org.equeim.tremotesf#0
07-19 21:17:45.028 W/SurfaceFlinger(698): Attempting to set client state on removed layer: org.equeim.tremotesf/org.equeim.tremotesf.torrentpropertiesactivity.TorrentPropertiesActivity#0
07-19 21:17:45.028 W/SurfaceFlinger(698): Attempting to destroy on removed layer: b89c82 org.equeim.tremotesf/org.equeim.tremotesf.torrentpropertiesactivity.TorrentPropertiesActivity#0
07-19 21:17:45.028 W/SurfaceFlinger(698): Attempting to destroy on removed layer: org.equeim.tremotesf/org.equeim.tremotesf.torrentpropertiesactivity.TorrentPropertiesActivity#0
07-19 21:17:45.028 W/SurfaceFlinger(698): Attempting to destroy on removed layer: AppWindowToken{af51af7 token=Token{d6b06f6 ActivityRecord{2db3791 u0 org.equeim.tremotesf/.torrentpropertiesactivity.TorrentPropertiesActivity t81}}}#0
07-19 21:17:45.028 W/SurfaceFlinger(698): Attempting to destroy on removed layer: AppWindowToken{313ea9b token=Token{fb27eaa ActivityRecord{d03ad95 u0 org.equeim.tremotesf/.mainactivity.MainActivity t81}}}#0

**Comment by ngoquang2708** [comment]
I can confirm this.

**Comment by equeim** [comment]
Hmm, that doesn't look like full stack trace, doesn't even have name of exception. What differs that torrent from others? I.e. did it have different state, settings, etc?

**Comment by Sak94664** [comment]
it is set seed regardless of ratio and seed regardleds of activity.
Oh,I found why the app is crashed.
When the torrent is set seed regardless of activity,the app will crash when entering peers&limits section.

**Comment by ngoquang2708** [comment]
Just tested what @Sak94664 and now the app crashes everytime I click Peers tab or Limits tab.
