### ISSUE TITLE
App freezes complete Android

### ISSUE THREAD

**Issue by pseiler** [equeim/tremotesf-android#34]
I use tremotesf with an openvpn to connect to my transmission-daemon in my home network. This worked very well until the amount of torrents growthed to much. When I reached some kind of limit (~1500 torrents) most of the time tremotesf completly freezed my android 9.0 smartphone with linageos installed on it. I haven't encountered this kind of issue on any other app. Sometime when waiting a lot time (~30 mins) it works again. Sometimes not.

The issue occurs when initially connecting to the server. If all the data was parsed initially it also works well.
It freezes at some point when it shows the connecting ring.

My assumption is, that parsing or collection that much information at a short time breaks the app. The app transdroid meanwhile still works very well (but doesn't have some cool features tremotesf has). The built-in webui of transmission-daemon also works well with this many torrents.

If I can activate logging or stuff, I will provide more infos.

**Comment by pseiler** [comment]
Looks promising. Thank you very much @equeim 
I'll test it, when a new app version is published.

**Comment by pseiler** [comment]
@equeim. Unfortunately the latest build crashes tremotesf completely when connecting to my transmission-daemon. I tried the arm and the arm64 build of v1.9.2

**Comment by equeim** [comment]
Could you please send me a logcat of crash?

**Comment by pseiler** [comment]
yes. Here it is. I hope it has everything you need. I can see a stack trace ;)
It was from the arm64 _*.apk_
https://pastebin.com/8SR6scR1

**Comment by pseiler** [comment]
@equeim 
Could you reopen the issue until this is fixed?

Btw. I donated you a tiny appreciation.
I also requested to localize your app into german on transifex

**Comment by equeim** [comment]
That's different issue, freeze is actually fixed. I created another issue for this (#35).
Thanks for donation!
