### ISSUE TITLE
feature request: add web seed function

### ISSUE THREAD

**Issue by Sak94664** [equeim/tremotesf-android#39]
If it's enabled,it is convenient to add direct http(s) link to the seed to promote download speed especially when there aren't many seeders available.
And we can check download speed for each web seed.
As far as I know,some of linux distributions enabled web seed for their torrents. :)

**Comment by equeim** [comment]
As far as I know, Transmission doesn't support adding web seeds to existing torrents yet, they should be specified in the torrent file / magnet link. Only thing it can do is show a list of existing web seeds and number of web seeds that we are currently downloading from (it is not yet supported by Tremotesf though).

**Comment by Sak94664** [comment]
`Transmission doesn't support adding web seeds to existing torrents yet,
`
oh,sorry,I was wrong.

But could you add the ability to view webseeds and each webseed's download speed?
(it's a bit weird to see download speed is not zero while peer count is zero,haha)

**Comment by equeim** [comment]
AFAIK, it is not possible. I can only get number of webseeds that torrent is currently being downloaded from and each webseed's URL, but not download speed per webseed.

**Comment by Sak94664** [comment]
I tried to check webseed detail in WebUI,but it only shows the number of webseed.And transmission-qt also only shows the number of webseed  
  
(transmission-gtk has this function,but maybe it's because transmission-gtk is different from transmission-daemon?)

**Comment by Sak94664** [comment]
I think it is not that important.
Transmission mainly focus on p2p file sharing but not centralized http download ;)
