### ISSUE TITLE
connect to Transmission over Tor, with .onion support

### ISSUE THREAD

**Issue by eighthave** [equeim/tremotesf-android#40]
Tor Onion Services provide a private way to securely connect to network services.  They are also easier to setup and run than HTTPS.  It would be great if tremotesf supported .onion addresses.  Then someone can install Transmission on a home server, enable the .onion address for it, then privately and securely reach Transmission from anywhere on the Internet.

The easy way to do this is just add support for HTTP CONNECT and/or SOCKS proxy settings.  Then the Orbot app will provide Tor to Tremotesf when the user sets the proxy settings.  There are somethings that can be added to make that easier to do, like an "Orbot" or "Tor" proxy setting that sets the proxy to SOCKS on _localhost_ on port 9050.

**Comment by equeim** [comment]
Isn't Orbot can do it by itself using Android's VPN service? Sadly, I'm not vary familiar with Orbot.

**Comment by eighthave** [comment]
Orbot's VPN mode can force the connection to happen over Tor, but it cannot always force the DNS to happen over Tor.  .onion addresses can only be resolved by Tor.  If a device is using DNS-over-TLS or DNS-over-HTTPS, then Orbot VPN mode cannot change the DNS resolver.  The app must either use a proxy or have support for Tor built-in to ensure that the .onion names are resolveable.  The NetCipher library makes building in Tor support easy, but proxying is enough to get things working.

**Comment by equeim** [comment]
That shouldn't be hard to implement, it seems that Qt supports DNS over proxy. I will add this in the next feature release.

**Comment by equeim** [comment]
Done.
