### ISSUE TITLE
Add 'share' action

### ISSUE THREAD

**Issue by pataquets** [equeim/tremotesf-android#42]
It would come very handy to share torrents with friends via chat/email or to be able to send the same torrent to another server (see #41).
Sharing a magnet URI would be enough, I guess.

**Comment by Sak94664** [comment]
you can view its hash in torrent's detail section
From the hash you can get a magnet link.  

if its hash is abcdef  
the magnet link will be   
magnet:?xt=urn:btih:abcdef

**Comment by pataquets** [comment]
Thanks for the tips, @Sak94664 
I'm aware of the hash being in the details. However, copying and pasting into a magnet link is somewhat cumbersome.
I need the magnet link to open as an Android share action to send via mail, messaging, etc. Even to other transmission apps, other Tremotesf servers, seedboxes, cloud torrenting services, torrent media players, etc. Thus, going to the servers to get the torrent file is also very unconvenient.
