### ISSUE TITLE
Download directory filter doesn't work correctly

### ISSUE THREAD

**Issue by SiIky** [equeim/tremotesf-android#48]
On the download directories list, all paths have the trailling `/` removed -- even paths that should have it (looking at the output of `transmission-remote -t <torrent> -i`) -- and (this is me guessing) these are used to filter torrents. However, (also me guessing) since Tremotesf uses string comparison, the filter doesn't give the right results.

I tested this by adding and removing the trailling `/` to some torrents with `transmission-remote`: when I remove the trailling `/` from some torrent, it shows up in the results; when I add the trailling `/` it doesn't show up anymore.

If you can point me to where changes are required, I can try to provide a PR. I can't build/test/etc, though, because I don't have a clue on how to do that for Android.

**Comment by equeim** [comment]
Thanks for the report!

**Comment by SiIky** [comment]
Thanks for fixing it! :)

**Comment by SiIky** [comment]
Just installed the new version and can confirm that it's working! Thanks again!
