### ISSUE TITLE
Alternative limits don't work properly

### ISSUE THREAD

**Issue by Nomeji** [equeim/tremotesf-android#53]
In server settings, alternative limits input don't work properly.

![Screenshot_20210305-164205](https://user-images.githubusercontent.com/5839114/110138681-82714e80-7dd2-11eb-97f8-63ed46e00944.png)

The download input control both download and upload speed while the upload input simply doesn't do anything.
Probably just a variable name mismatch. I didn't investigate much for now.

**Comment by equeim** [comment]
Thanks, fixed.
