### ISSUE TITLE
Include Transmission in the Application

### ISSUE THREAD

**Issue by varbhat** [equeim/tremotesf-android#61]
I currently run transmission in termux and use this app. It works great.

But, it would be even better if tremotesf comes with transmission included. compile transmission statically for aarch64 , then you can include in lib directory where it can be marked executable and run.

So,that tremotesf will be another torrent application for android.

Can't this be done?

**Comment by varbhat** [comment]
@equeim have you seen this?

**Comment by equeim** [comment]
I'm not sure that running transmission-daemon as-is is a good idea. Android 12 seems to have new restrictions for non-Java processes (see https://github.com/termux/termux-app/issues/2366). AFAIK it is possible to use transmission as native library inside regular Android service though. I will have to do some research on that.
What I most worried about is app size. It is already quite large and including transmission will make it even bigger.

**Comment by varbhat** [comment]
1) regarding size, you can provide -with-daemon and -without-daemon variants. or you can provide transmission-daemon as seperate app.
2) regarding native library, you can still include binary in /lib/arch i think. just `chmod +x` on new files not embedded is restricted,i think.
3) i am currently using termux for transmission daemon but i would prefer it to be within tremotesf . please do it.
