### ISSUE TITLE
GET parameters get encoded badly

### ISSUE THREAD

**Issue by gergovari** [equeim/tremotesf-android#63]
An older Transmission client makes this request:
```
uri="/transmission/rpc?token=asd"
```
while Tremotesf:
```
uri="/transmission/rpc%3Ftoken=asd"
```
thus making it impossible to add GET parameters.

**Comment by equeim** [comment]
Are you referring to server API path in connection settings?

**Comment by thegergo02** [comment]
@equeim Is this fixed? I see some activity on it but the issue hasn't been closed yet. (I'm asking because my new server might use Transmission again :) ).

**Comment by equeim** [comment]
Sorry for the late answer, I believe it should be fixed now.
